### ISSUE TITLE
How to create button?

### ISSUE THREAD

**Issue by ranrinc** [gundamew/botman-driver-line#7]
I'm trying to create button which usually work across the board.. but how do I create buttons? or Horizontal Carousel? Help?

**Comment by ranrinc** [comment]
@gundamew hi... did you read my message? Help?

**Comment by gundamew** [comment]
Sorry for the delayed response. Please see the “[Sending Facebook Templates](https://botman.io/2.0/driver-facebook-messenger#sending-facebook-templates)” section of Facebook driver document for your reference.
